dist: xenial
sudo: required
language: ruby
rvm:
  - 2.3

install:
  - gem install dapp --version=0.19
  #- sudo apt-get update -qq
  #- sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
  #- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  #- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  #- sudo apt-get update -qq
  #- sudo apt-get -o dpkg::options::="--force-confnew" install -y docker-ce=17.09.0~ce-0~ubuntu
  #- USER_NAME=$(id -un) && sudo gpasswd -a $USER_NAME docker
  #- sudo service docker restart
  #- sudo docker version

script:
  - docker version
