dist: xenial
sudo: required
language: ruby
rvm:
  - 2.3

install:
  - curl https://raw.githubusercontent.com/flant/dapp/master/install.sh | bash -s 0.19
  - dapp update
  - dapp --version
  - docker version

script:
  - dapp dimg build

after_success:
  - if [ -n "$TRAVIS_TAG" ] ; then docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASSWORD && dapp dimg spush dappdeps/core --tag $TRAVIS_TAG ; fi

branches:
  only:
    - master
