dist: xenial
sudo: required
language: ruby
rvm:
  - 2.3

install:
  - curl https://raw.githubusercontent.com/flant/dapp/master/install.sh | bash -s 0.19
  - dapp update
  - dapp --version
  - docker version

script:
  - ./build_and_push.sh

branches:
  only:
    - master
